In [2]:
import numpy as np

In [3]:
myArray = np.arange(0,20)

In [4]:
myArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
myArray[3:10]

array([3, 4, 5, 6, 7, 8, 9])

In [6]:
myArray[0:2] = 0

In [7]:
myArray

array([ 0,  0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
sliceArray = myArray[0:10]

In [9]:
sliceArray

array([0, 0, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
sliceArray[:] = 700

In [11]:
sliceArray #buradaki tüm elemanlara 700 sayısını bu şekilde atayabiliriz.

array([700, 700, 700, 700, 700, 700, 700, 700, 700, 700])

In [12]:
myArray #yukarıdaki değişim myArrayi değiştirir / yansıtılır.

array([700, 700, 700, 700, 700, 700, 700, 700, 700, 700,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [13]:
exArray = np.arange(0,10)

In [14]:
exArrayCopy = exArray.copy()

In [15]:
exArrayCopy[:] = 10

In [16]:
exArrayCopy # eğer bu yöntemle yazarsak diğer değişkeni etkilemeyiz.

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [17]:
exArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Matrix

In [18]:
exampleMatrix = [[10,20,30],[40,50,60],[70,80,90]]

In [19]:
matrix = np.array(exampleMatrix)

In [20]:
matrix

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [21]:
matrix[0]

array([10, 20, 30])

In [22]:
matrix[1][2]

60

In [23]:
matrix[1,2]

60

In [24]:
matrix[0:,2] #0.satırdan başlayıp 2.sütundakileri alır.

array([30, 60, 90])

In [25]:
matrix[1,1:] #1.satırda, 1'den sonrakileri alır.

array([50, 60])

In [26]:
matrix[1:,1:]

array([[50, 60],
       [80, 90]])

In [27]:
newMatrix = [[10,20,30,40],[50,60,70,80],[90,100,110,120],[130,140,150,160]]

In [28]:
newMatrix = np.array(newMatrix)

In [29]:
newMatrix


array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [32]:
newMatrix[[0,1,3]] #0, 1 ve 3. indeksleri döndürür.

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [130, 140, 150, 160]])

## Operasyonlar

In [35]:
opMatrix = np.random.randint(1,100,20)

In [36]:
opMatrix

array([14,  4, 76, 12, 32, 23, 66, 80, 53, 20, 84, 88,  5, 22, 19, 91,  7,
       42,  3, 52])

In [37]:
opMatrix > 50

array([False, False,  True, False, False, False,  True,  True,  True,
       False,  True,  True, False, False, False,  True, False, False,
       False,  True])

In [39]:
opMatrix + opMatrix # dizi ile dizi toplama

array([ 28,   8, 152,  24,  64,  46, 132, 160, 106,  40, 168, 176,  10,
        44,  38, 182,  14,  84,   6, 104])

In [40]:
opMatrix * opMatrix

array([ 196,   16, 5776,  144, 1024,  529, 4356, 6400, 2809,  400, 7056,
       7744,   25,  484,  361, 8281,   49, 1764,    9, 2704])

In [41]:
opMatrix - opMatrix

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [42]:
opMatrix / opMatrix

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [44]:
np.sqrt(opMatrix) #karekökü alınır.

array([3.74165739, 2.        , 8.71779789, 3.46410162, 5.65685425,
       4.79583152, 8.1240384 , 8.94427191, 7.28010989, 4.47213595,
       9.16515139, 9.38083152, 2.23606798, 4.69041576, 4.35889894,
       9.53939201, 2.64575131, 6.4807407 , 1.73205081, 7.21110255])

In [45]:
np.max(opMatrix)

91

In [46]:
np.min(opMatrix)

3