In [1]:
import numpy as np

In [2]:
myArray = np.arange(0,20)

In [3]:
myArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
myArray[3:10]

array([3, 4, 5, 6, 7, 8, 9])

In [5]:
myArray[0:2] = 0

In [6]:
myArray

array([ 0,  0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
sliceArray = myArray[0:10]

In [8]:
sliceArray

array([0, 0, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
sliceArray[:] = 700

In [12]:
sliceArray #buradaki tüm elemanlara 700 sayısını bu şekilde atayabiliriz.

array([700, 700, 700, 700, 700, 700, 700, 700, 700, 700])

In [14]:
myArray #yukarıdaki değişim myArrayi değiştirir / yansıtılır.

array([700, 700, 700, 700, 700, 700, 700, 700, 700, 700,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [15]:
exArray = np.arange(0,10)

In [16]:
exArrayCopy = exArray.copy()

In [17]:
exArrayCopy[:] = 10

In [20]:
exArrayCopy # eğer bu yöntemle yazarsak diğer değişkeni etkilemeyiz.

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [19]:
exArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Matrix

In [21]:
exampleMatrix = [[10,20,30],[40,50,60],[70,80,90]]

In [23]:
np.array(exampleMatrix)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])